# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cceb432d691cf558992eed8ee5e06aae580fb0c43e14126cf606e44d2b77bde60756c19b3a05fd4a4a69557d854f9a202add12805a4e9c8c91fb801c8eed6661

test:
  secret_key_base: d0305932bd01a85836acba0eb871ea53657e3660bd77517b04c5cfd6395ad2affe164b3a4d4fc04f72dce1f157bfe7da9770d85a2417dd7d7e5d25cd9659b495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
